import java.awt.print.Book;
/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
/**
*
* @author Student 054
*/
public class myframe extends javax.swing.JFrame {
    book[] books=new book[100];
    int count=0;

    public myframe(){
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255,255,153));
    }

    void addBook(){
        String title=booktitle.getText();
        String author=bookauthor.getText();
        books[count]=new book(title,author);
        count++;
        result.setText("Book added successfully!");
    }

    void searchByTitle(){
        String title=booktitle.getText();
        boolean found=false;
        for(int i=0;i<count;i++){
            if(books[i].title.equalsIgnoreCase(title)){
                result.setText("Book Found!\nTitle: "+books[i].title+"\nAuthor: "+books[i].author);
                found=true;
                break;
            }
        }
        if (!found){
            result.setText("Book not found.");
        }
    }

    void searchByAuthor(){
        String author=bookauthor.getText();
        boolean found=false;
        for(int i=0;i<count;i++){
            if(books[i].author.equalsIgnoreCase(author)){
                result.setText("Book Found!\nTitle: "+books[i].title+"\nAuthor: "+books[i].author);
                found=true;
                break;
            }
        }
        if (!found){
            result.setText("Book not found.");
        }
    }

    void displayBook(){
        result.setText("");
        for(int i=0;i<count;i++){
            result.append("Title: "+books[i].title+" | Author: "+books[i].author+"\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bookauthor = new javax.swing.JTextField();
        booktitle = new javax.swing.JTextField();
        searchbytitle = new javax.swing.JButton();
        searchbyauthor = new javax.swing.JButton();
        displaybooks = new javax.swing.JButton();
        addbook = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Book Title: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Book Author: ");

        bookauthor.setBackground(new java.awt.Color(255, 153, 153));
        bookauthor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bookauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookauthorActionPerformed(evt);
            }
        });

        booktitle.setBackground(new java.awt.Color(255, 153, 153));
        booktitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        booktitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booktitleActionPerformed(evt);
            }
        });

        searchbytitle.setBackground(new java.awt.Color(255, 153, 153));
        searchbytitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchbytitle.setForeground(new java.awt.Color(51, 0, 0));
        searchbytitle.setText("Search by Title");
        searchbytitle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchbytitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbytitleActionPerformed(evt);
            }
        });

        searchbyauthor.setBackground(new java.awt.Color(255, 153, 153));
        searchbyauthor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchbyauthor.setForeground(new java.awt.Color(51, 0, 0));
        searchbyauthor.setText("Search by Author");
        searchbyauthor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchbyauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbyauthorActionPerformed(evt);
            }
        });

        displaybooks.setBackground(new java.awt.Color(255, 153, 153));
        displaybooks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        displaybooks.setForeground(new java.awt.Color(51, 0, 0));
        displaybooks.setText("Display Books");
        displaybooks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        displaybooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybooksActionPerformed(evt);
            }
        });

        addbook.setBackground(new java.awt.Color(255, 153, 153));
        addbook.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addbook.setForeground(new java.awt.Color(51, 0, 0));
        addbook.setText("Add Book");
        addbook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbookActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BOOK SEARCH APPLICATION");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 153));

        result.setBackground(new java.awt.Color(204, 255, 204));
        result.setColumns(20);
        result.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        result.setRows(5);
        jScrollPane1.setViewportView(result);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student 054\\Pictures\\patro.PNG")); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student 054\\Pictures\\1984.PNG")); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student 054\\Pictures\\books.PNG")); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student 054\\Pictures\\hp.PNG")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                            layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(27, 27, 27)
                            .addComponent(booktitle, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                            layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bookauthor)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup()
                        .addComponent(searchbytitle, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displaybooks, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup()
                        .addComponent(addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(searchbyauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(booktitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchbyauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchbytitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displaybooks, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void bookauthorActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void booktitleActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void searchbytitleActionPerformed(java.awt.event.ActionEvent evt) {
        searchByTitle();
    }

    private void searchbyauthorActionPerformed(java.awt.event.ActionEvent evt) {
        searchByAuthor();
    }

    private void displaybooksActionPerformed(java.awt.event.ActionEvent evt) {
        displayBook();
    }

    private void addbookActionPerformed(java.awt.event.ActionEvent evt) {
        addBook();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton addbook;
    private javax.swing.JTextField bookauthor;
    private javax.swing.JTextField booktitle;
    private javax.swing.JButton displaybooks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea result;
    private javax.swing.JButton searchbyauthor;
    private javax.swing.JButton searchbytitle;
    // End of variables declaration
}
